config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'accounts#index'
  resources :accounts, only: [:index] do
    member do
      get '/atm', to: 'accounts#atm'
      post '/deposit', to: 'accounts#deposit'
      post '/withdraw', to: 'accounts#withdraw'
      post '/unfreeze', to: 'accounts#unfreeze'
    end
  end
end

app/models/account.rb
class Account < ApplicationRecord
    
    has_many :transactions
    validates :name, uniqueness: true
    validates :name, :category, presence: true
    
    after_save :check_suspension
    
    def deposits()
        self.transactions.where(category: 'Deposit')
    end
    
    def withdraws()
        self.transactions.where(category: 'Withdraw')
    end
    
    def overdrafts()
        self.transactions.where(category: 'Overdraft')
    end
    
    def deposit(amount)
   
        
        return if check_amount(amount).any?
        
        ActiveRecord::Base.transaction do
            self.update!(balance: self.balance + amount)
            #raise 'explode'
            Transaction.create!(amount: amount, category: 'Deposit' , account_id: self.id)
        end
    end
    
    def withdraw(amount)
        
        return if check_amount(amount).any?
        
        return if check_account_suspension().any?
        
        if  self.balance >= amount
            ActiveRecord::Base.transaction do
                self.update!(balance: self.balance - amount)
                Transaction.create!(amount: amount, category: 'Withdraw' , account_id: self.id)
            end
        else
            ActiveRecord::Base.transaction do
                self.update!(balance: self.balance - 50, flags: self.flags+1)
                Transaction.create!(amount: 50, category: 'Overdraft' , account_id: self.id)
            end
            
        end
    end
    
    def clear_suspension
        return if insufficent_funds
          ActiveRecord::Base.transaction do
                self.update!(balance: self.balance - 100, is_suspended: false)
                Transaction.create!(amount: 100, category: 'Unfreeze' , account_id: self.id)
            end
        
    end
    
    private 
    
    def insufficent_funds
     self.errors.add(:account, 'does not have insufficent funds') if self.balance <100
     self.errors.any?
    end
    
    def check_amount(amount)
    
        if !amount.is_a? Numeric
            self.errors.add(:amount, 'not a number') 
        end
        
        self.errors.add(:amount, 'less than zero') if amount<=0
        self.errors
    end
    
    def check_suspension()
        
        if self.flags > 3
            self.update!(is_suspended: true, flags: 0)
        end
        
    end
    
    def check_account_suspension()
        if self.flags > 3
            self.errors.add(:account, 'account is suspended.') 
        end
        self.errors
    end
    
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/transaction.rb
class Transaction < ApplicationRecord
    belongs_to :account
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
    
    def index
        @accounts = Account.order(id: :desc)
    end
    
    def atm
        @account = Account.find(params[:id])
        
    end
    
    def deposit
        @account = Account.find(params[:id])
        @account.deposit(params[:amount].to_f)
        
        if @account.errors.any?
            render 'atm'
        else
            redirect_to root_url
        end
    end
    
    def withdraw
        
        @account = Account.find(params[:id])
        @account.withdraw(params[:amount].to_f)
        
        if @account.errors.any?
            render 'atm'
        else
            redirect_to root_url
        end
        
    end
    
    def unfreeze
        @account = Account.find(params[:id])
        @account.clear_suspension()
        
        if @account.errors.any?
            render 'atm'
        else
            redirect_to root_url
        end
    end
    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/accounts/atm.html.erb
<h2 class="display-4">ATM for <%= @account.name%></h2>

<div class="row">
    <div class="col">
        <% if @account.errors.any? %>
            <h2>There were <%= @account.errors.count %></h2>
            <ul>
                <%= @account.errors.full_messages.each  do |msg|%>
                    <li> <%= msg %></li>
                <% end %>
            </ul>
        <% end %>
    </div>
    
</div>

<div class="row">
    
    <div class ="col">
        <%= form_with(url: deposit_account_path(@account), local:true, method: 'post') do |form| %>
        
        <div class ="form-group" >
            <%= form.label :amount %>
            <%= form.text_field :amount, id: :amount, class: 'form-control' %>
            
        </div>
        <div class ="form-group" >
        
            <%= form.submit 'Deposit', class:'btn btn-success' %>
            
        </div>
        <% end %>
    </div>
    
 
    <div class ="col">
        <%= form_with(url: withdraw_account_path(@account), local:true, method: 'post') do |form| %>
        
        <div class ="form-group" >
            <%= form.label :amount %>
            <%= form.text_field :amount, id: :amount, class: 'form-control' %>
            
        </div>
        <div class ="form-group" >
        
            <%= form.submit 'Withdraw', class:'btn btn-success' %>
            
        </div>
        <% end %>
    </div>
        

    <div class ="col">
        
        <%= form_with(url: unfreeze_account_path(@account), local:true, method: 'post') do |form| %>
        
        <div class ="form-group" >
           
        </div>
        <div class ="form-group" >
        
            <%= form.submit 'Clear Suspension', class:'btn btn-success' %>
            
        </div>
        <% end %>
        
        
    </div>
    
</div>

app/views/accounts/index.html.erb
<h2 class="display-4">Account List</h2>

<table class="table table-striped">
    
    <theadc class="thead-inverse">
        <tr>
            <th>Id</th>
            <th>Name</th>
            <th>Type</th>
            <th>Balance</th>
            <th>Flags</th>
            <th>Suspended?</th>
        </tr>
    </thead>
    <tbody>
            <% @accounts.each do |a| %>
            <tr>
                <td><%= a.id %></td>
                <td>
                    <%= link_to a.name,atm_account_path(a) %>
                </td>
                <td><%= a.category %></td>
                <td><%= number_to_currency a.balance %></td>
                <td><%= a.flags %></td>
                <td><%= a.is_suspended %></td>
            </tr>
            <% end %>
      
    </tbody>
</table>

app/views/application/_nav.html.erb
<nav class="navbar navbar-toggleable-md navbar-light bg-faded">
  <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <a class="navbar-brand" href="/">My Bank</a>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <a class="nav-link" href="/">Home</a>
      </li>
     
    </ul>
   
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bank</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'nav' %>
    <div class = "container-fluid">
      <div class="row">
        <div class="col">
           <%= yield %>
        </div>
      </div>
    </div>
   
  </body>
</html>